### ISSUE TITLE
اینجا جای ذخیره  ی پسورد نیست

### ISSUE THREAD

**Issue by ArdeshirV** [hsamfm/passwd_txt#1]
با درود

اینجا یک رپوسیتوری عمومیست و جای ذخیره ی پسورد نیست. برای اینکار باید حتما نخست پسورد خود را انکریپت کنید سپس در یک فضای ابری انکریپت شده ی امن آنرا بارگذاری کنید.  اساسا بخاطر تحریم ها گیت هاب اجازه ی ساختن رپوسیتوری خصوصی را هم به ما نخواهد داد.

اما چه باید کرد؟

برای مثال حداقل از یک ابزار رمزنگاری متن بسیار ساده مانند این که خودم ساختم یا بهتر از آن برای انکریپت کردن فایل پسورد خود استفاده کنید:
https://github.com/ArdeshirV/Encrypt-String

نرم افزارهای بسیار حرفه ای هم برای ذخیره ی پسورد موجودند که من این را توصیه می کنم:
https://keepass.info/download.html

سپس دیتابیس آنرا در یک فضای ابری انکریپت شده ی فوق امن(نه از آنها که گوگل یا مایکروسافت دارند) و خصوصی مانند این آپلود کنید:
https://mega.nz/

پیروز باشید؛
اردشیر

**Comment by hsamfm** [comment]
ممنون من اصلا حواسم به این فایل نبود بابت به یاد انداختن شما
